/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CRUD.crudFunction;
import javax.swing.JOptionPane;
import java.util.Arrays;



/**
 *
 * @author USER
 */
public class frameBerkas extends javax.swing.JFrame {
    
    private crudFunction CRUD;
    
    private String namaTabel = "tb_berkas"; 
    private String primaryKey = "id_berkas";
    private String fieldnya[] = {"id_berkas", "id_anggota", "tgl_upload", "status_berkas"};
    private String[] isinya;
    
    private String judulKolom[] = {"ID Berkas", "ID Anggota", "Tanggal Upload", "Status Berkas"}; 
    private int lebarKolom[] = {100, 100, 250, 100};
    private String SQL = "SELECT * FROM tb_berkas ORDER BY id_berkas ASC";

    /**
     * Creates new form frameBerkas
     */
    public frameBerkas() {
        
        CRUD = new crudFunction();
        
        isinya = new String[4];
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        loadData();
    }
    
    public void loadData(){
        CRUD.settingJudulTabel(tabelBerkas, judulKolom);
        CRUD.settingLebarKolom(tabelBerkas, lebarKolom);
        CRUD.tampilTabel(tabelBerkas, SQL, judulKolom);
    }
    
    private void updateIsinya() {
        isinya[0] = textIdBerkas.getText();
        isinya[1] = textIdAnggota.getText();
        isinya[2] = textStatusBerkas.getSelectedItem().toString();
        isinya[3] = textTglUpload.getText();
    }
    
    private void bersih() {
        textIdBerkas.setText("");
        textIdAnggota.setText("");
        textTglUpload.setText("");
        textStatusBerkas.setSelectedItem("Diterima"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tanggalUpload = new javax.swing.JLabel();
        idBerkas = new javax.swing.JLabel();
        idAnggota = new javax.swing.JLabel();
        statusBerkas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textIdBerkas = new javax.swing.JTextField();
        textIdAnggota = new javax.swing.JTextField();
        textTglUpload = new javax.swing.JTextField();
        textStatusBerkas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBersih = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBerkas = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Frame Berkas");
        setResizable(false);

        tanggalUpload.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalUpload.setText("Tanggal Upload");

        idBerkas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idBerkas.setText("Id Berkas");

        idAnggota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idAnggota.setText("Id Anggota");

        statusBerkas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusBerkas.setText("Status Berkas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBerkas)
                    .addComponent(idAnggota)
                    .addComponent(idBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalUpload))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idBerkas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggalUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusBerkas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textTglUpload.setToolTipText("YYYY-MM-DD");

        textStatusBerkas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diterima", "Ditolak" }));
        textStatusBerkas.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textIdBerkas, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(textIdAnggota)
                    .addComponent(textTglUpload)
                    .addComponent(textStatusBerkas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textIdBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textTglUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textStatusBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSimpan);

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        jPanel3.add(buttonUbah);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel3.add(buttonHapus);

        buttonBersih.setText("Bersih");
        buttonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBersih);

        buttonCetak.setText("Cetak");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCetak);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Data Berkas");
        jPanel4.add(jLabel2);

        tabelBerkas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBerkas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBerkasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBerkas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihActionPerformed
        // TODO add your handling code here:
        
        bersih();
        textIdBerkas.requestFocus();
    }//GEN-LAST:event_buttonBersihActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        
        updateIsinya();
        
        if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom terlebih dahulu jika ingin menggunakan tombol Simpan...!");
        } else {
            CRUD.SimpanDinamis(namaTabel, fieldnya, isinya);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdBerkas.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Harap isi 'Id Berkas' yang ingin diubah jika ingin menggunakan tombol Ubah...!");
            bersih();
            textIdBerkas.requestFocus();
        } else if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang kosong jika ingin menggunakan tombol Ubah...!");
        } else {
            CRUD.UbahDinamis(namaTabel, primaryKey, isiPrimary, fieldnya, isinya);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdBerkas.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi 'Id Berkas' yang ingin dihapus jika ingin menggunakan tombol Hapus...!");
            bersih();
            textIdBerkas.requestFocus();
        } else {
            CRUD.HapusDinamis(namaTabel, primaryKey, isiPrimary);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tabelBerkasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBerkasMouseClicked
        // TODO add your handling code here:
        
        int row = tabelBerkas.getSelectedRow();

            if (row != -1) {
                String valueId = tabelBerkas.getValueAt(row, 0).toString();
                String valueBerkas = tabelBerkas.getValueAt(row, 1).toString();
                String valueTanggalUpload = tabelBerkas.getValueAt(row, 2).toString();
                String valueStatusBerkas = tabelBerkas.getValueAt(row, 3).toString();

                textIdAnggota.setText(valueId);
                textIdBerkas.setText(valueBerkas);
                textTglUpload.setText(valueTanggalUpload);
                textStatusBerkas.setSelectedItem(valueStatusBerkas);
            }
    }//GEN-LAST:event_tabelBerkasMouseClicked

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        
        CRUD.cetakLaporan("laporanBerkas.jasper");
    }//GEN-LAST:event_buttonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBerkas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBerkas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBerkas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBerkas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameBerkas().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBersih;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel idAnggota;
    private javax.swing.JLabel idBerkas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel statusBerkas;
    private javax.swing.JTable tabelBerkas;
    private javax.swing.JLabel tanggalUpload;
    private javax.swing.JTextField textIdAnggota;
    private javax.swing.JTextField textIdBerkas;
    private javax.swing.JComboBox<String> textStatusBerkas;
    private javax.swing.JTextField textTglUpload;
    // End of variables declaration//GEN-END:variables
}
