/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CRUD.crudFunction;
import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author USER
 */
public class frameAnggota extends javax.swing.JFrame {
    
    private crudFunction CRUD;
    
    private String namaTabel = "tb_anggota"; 
    private String primaryKey = "id_anggota";
    private String fieldnya[] = {"id_anggota", "nik", "nama", "alamat", "tgl_lahir", "jenis_kelamin", "status"};
    private String[] isinya;
    
    private String judulKolom[] = {"ID Anggota", "NIK", "Nama", "Alamat", "Tanggal Lahir", "Jenis Kelamin", "Status"}; 
    private int lebarKolom[] = {100, 200, 150, 150, 150, 100, 100};
    private String SQL = "SELECT * FROM tb_anggota ORDER BY id_anggota ASC";
    

    /**
     * Creates new form frameAnggota
     */
    public frameAnggota() {
        
        CRUD = new crudFunction();
                
        isinya = new String[7];
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        loadData();
    }
    
    public void loadData(){
        CRUD.settingJudulTabel(tabelAnggota, judulKolom);
        CRUD.settingLebarKolom(tabelAnggota, lebarKolom);
        CRUD.tampilTabel(tabelAnggota, SQL, judulKolom);
    }
    
    private void updateIsinya() {
        isinya[0] = textIdAnggota.getText();
        isinya[1] = textNik.getText();
        isinya[2] = textNama.getText();
        isinya[3] = textAlamat.getText();
        isinya[4] = textTanggalLahir.getText();
        isinya[5] = textJenisKelamin.getSelectedItem().toString();
        isinya[6] = textStatus.getSelectedItem().toString();
    }
    
    private void bersih() {
        textIdAnggota.setText("");
        textNik.setText("");
        textNama.setText("");
        textAlamat.setText("");
        textTanggalLahir.setText("");
        textJenisKelamin.setSelectedItem("Laki-laki");
        textStatus.setSelectedItem("Aktif");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        idAnggota = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        tanggalLahir = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textIdAnggota = new javax.swing.JTextField();
        textNik = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        textTanggalLahir = new javax.swing.JTextField();
        textJenisKelamin = new javax.swing.JComboBox<>();
        textStatus = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBersih = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Frame Anggota");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        idAnggota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idAnggota.setText("Id Anggota");

        nik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nik.setText("NIK");

        nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama.setText("Nama");

        alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamat.setText("Alamat");

        tanggalLahir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalLahir.setText("Tanggal Lahir");

        jenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenisKelamin.setText("Jenis Kelamin");

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idAnggota)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat)
                    .addComponent(tanggalLahir)
                    .addComponent(jenisKelamin)
                    .addComponent(status))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(idAnggota)
                .addGap(12, 12, 12)
                .addComponent(nik)
                .addGap(12, 12, 12)
                .addComponent(nama)
                .addGap(12, 12, 12)
                .addComponent(alamat)
                .addGap(18, 18, 18)
                .addComponent(tanggalLahir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jenisKelamin)
                .addGap(12, 12, 12)
                .addComponent(status)
                .addContainerGap())
        );

        textTanggalLahir.setToolTipText("YYYY-MM-DD");
        textTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTanggalLahirActionPerformed(evt);
            }
        });

        textJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        textJenisKelamin.setToolTipText("");

        textStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "NonAktif" }));
        textStatus.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTanggalLahir)
                    .addComponent(textAlamat)
                    .addComponent(textNama)
                    .addComponent(textNik)
                    .addComponent(textIdAnggota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(textIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSimpan);

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        jPanel3.add(buttonUbah);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel3.add(buttonHapus);

        buttonBersih.setText("Bersih");
        buttonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBersih);

        buttonCetak.setText("Cetak");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCetak);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DATA ANGGOTA");
        jPanel4.add(jLabel1);

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAnggota);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTanggalLahirActionPerformed

    private void buttonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihActionPerformed
        // TODO add your handling code here:
        
        bersih();
        textIdAnggota.requestFocus();
    }//GEN-LAST:event_buttonBersihActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        
        updateIsinya();
        
        if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom terlebih dahulu jika ingin menggunakan tombol Simpan...!");
        } else {
            CRUD.SimpanDinamis(namaTabel, fieldnya, isinya);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdAnggota.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Harap isi 'Id Anggota' yang ingin diubah jika ingin menggunakan tombol Ubah...!");
            bersih();
            textIdAnggota.requestFocus();
        } else if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang kosong jika ingin menggunakan tombol Ubah...!");
        } else {
            CRUD.UbahDinamis(namaTabel, primaryKey, isiPrimary, fieldnya, isinya);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdAnggota.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi 'Id Anggota' yang ingin dihapus jika ingin menggunakan tombol Hapus...!");
            bersih();
            textIdAnggota.requestFocus();
        } else {
            CRUD.HapusDinamis(namaTabel, primaryKey, isiPrimary);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        
        CRUD.cetakLaporan("laporanAnggota.jasper");
    }//GEN-LAST:event_buttonCetakActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        // TODO add your handling code here:
        
        int row = tabelAnggota.getSelectedRow();

            if (row != -1) {
                String valueId = tabelAnggota.getValueAt(row, 0).toString();
                String valueNik = tabelAnggota.getValueAt(row, 1).toString();
                String valueNama = tabelAnggota.getValueAt(row, 2).toString();
                String valueAlamat = tabelAnggota.getValueAt(row, 3).toString();
                String valueTanggalLahir = tabelAnggota.getValueAt(row, 4).toString();
                String valueJenisKelamin = tabelAnggota.getValueAt(row, 5).toString();
                String valueStatus = tabelAnggota.getValueAt(row, 6).toString();

                textIdAnggota.setText(valueId);
                textNik.setText(valueNik);
                textNama.setText(valueNama);
                textAlamat.setText(valueAlamat);
                textTanggalLahir.setText(valueTanggalLahir);
                textJenisKelamin.setSelectedItem(valueJenisKelamin);
                textStatus.setSelectedItem(valueStatus);
            }
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton buttonBersih;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel idAnggota;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nik;
    private javax.swing.JLabel status;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JLabel tanggalLahir;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textIdAnggota;
    private javax.swing.JComboBox<String> textJenisKelamin;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNik;
    private javax.swing.JComboBox<String> textStatus;
    private javax.swing.JTextField textTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
