/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CRUD.crudFunction;
import javax.swing.JOptionPane;
import java.util.Arrays;


/**
 *
 * @author USER
 */
public class frameDprd extends javax.swing.JFrame {
    
    private crudFunction CRUD;
    
    private String namaTabel = "tb_dprd"; 
    private String primaryKey = "id_dprd";
    private String fieldnya[] = {"id_dprd", "id_anggota", "periode_jabatan"};
    private String[] isinya;
    
    private String judulKolom[] = {"ID DPRD", "ID Anggota", "Periode Jabatan"}; 
    private int lebarKolom[] = {100, 100, 250};
    private String SQL = "SELECT * FROM tb_dprd ORDER BY id_dprd ASC";
    

    /**
     * Creates new form frameDprd
     */
    public frameDprd() {
        
        CRUD = new crudFunction();
                
        isinya = new String[3];
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        loadData();
    }
    
    public void loadData(){
        CRUD.settingJudulTabel(tabelDprd, judulKolom);
        CRUD.settingLebarKolom(tabelDprd, lebarKolom);
        CRUD.tampilTabel(tabelDprd, SQL, judulKolom);
    }
    
    private void updateIsinya() {
        isinya[0] = textIdDprd.getText();
        isinya[1] = textIdAnggota.getText();
        isinya[2] = textPeriodeJabatan.getText();
    }
    
    private void bersih() {
        textIdAnggota.setText("");
        textIdDprd.setText("");
        textPeriodeJabatan.setText(""); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tanggal = new javax.swing.JPanel();
        idDprd = new javax.swing.JLabel();
        idAnggota = new javax.swing.JLabel();
        periodeJabatan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textIdDprd = new javax.swing.JTextField();
        textIdAnggota = new javax.swing.JTextField();
        textPeriodeJabatan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBersih = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDprd = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Frame DPRD");
        setResizable(false);

        idDprd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idDprd.setText("Id DPRD");

        idAnggota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idAnggota.setText("Id Anggota");

        periodeJabatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        periodeJabatan.setText("Periode Jabatan");

        javax.swing.GroupLayout TanggalLayout = new javax.swing.GroupLayout(Tanggal);
        Tanggal.setLayout(TanggalLayout);
        TanggalLayout.setHorizontalGroup(
            TanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TanggalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(TanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodeJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addGroup(TanggalLayout.createSequentialGroup()
                        .addGroup(TanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idDprd)
                            .addComponent(idAnggota))
                        .addContainerGap())))
        );
        TanggalLayout.setVerticalGroup(
            TanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TanggalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(idDprd)
                .addGap(12, 12, 12)
                .addComponent(idAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(periodeJabatan)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textIdDprd, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(textIdAnggota)
                    .addComponent(textPeriodeJabatan))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textIdDprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPeriodeJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSimpan);

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        jPanel3.add(buttonUbah);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel3.add(buttonHapus);

        buttonBersih.setText("Bersih");
        buttonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBersih);

        buttonCetak.setText("Cetak");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCetak);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Data DPRD");
        jPanel4.add(jLabel1);

        tabelDprd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabelDprd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDprdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDprd);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihActionPerformed
        // TODO add your handling code here:

        bersih();
        textIdDprd.requestFocus();
    }//GEN-LAST:event_buttonBersihActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        
        updateIsinya();
        
        if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom terlebih dahulu jika ingin menggunakan tombol Simpan...!");
        } else {
            CRUD.SimpanDinamis(namaTabel, fieldnya, isinya);
            loadData();
            bersih();
        }
        
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdDprd.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Harap isi 'Id DPRD' yang ingin diubah jika ingin menggunakan tombol Ubah...!");
            bersih();
            textIdDprd.requestFocus();
        } else if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang kosong jika ingin menggunakan tombol Ubah...!");
        } else {
            CRUD.UbahDinamis(namaTabel, primaryKey, isiPrimary, fieldnya, isinya);
            loadData();
            bersih();
        }
        
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdDprd.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi 'Id DPRD' yang ingin dihapus jika ingin menggunakan tombol Hapus...!");
            bersih();
            textIdDprd.requestFocus();
        } else {
            CRUD.HapusDinamis(namaTabel, primaryKey, isiPrimary);
            loadData();
            bersih();
        }
        
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tabelDprdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDprdMouseClicked
        // TODO add your handling code here:
        
        int row = tabelDprd.getSelectedRow();

            if (row != -1) {
                String valueId = tabelDprd.getValueAt(row, 0).toString();
                String valueIdAnggota = tabelDprd.getValueAt(row, 1).toString();
                String valuePeriodeJabatan = tabelDprd.getValueAt(row, 2).toString();

                textIdDprd.setText(valueId);
                textIdAnggota.setText(valueIdAnggota);
                textPeriodeJabatan.setText(valuePeriodeJabatan);
            }
    }//GEN-LAST:event_tabelDprdMouseClicked

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        
        CRUD.cetakLaporan("laporanDprd.jasper");
    }//GEN-LAST:event_buttonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDprd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tanggal;
    private javax.swing.JButton buttonBersih;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel idAnggota;
    private javax.swing.JLabel idDprd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel periodeJabatan;
    private javax.swing.JTable tabelDprd;
    private javax.swing.JTextField textIdAnggota;
    private javax.swing.JTextField textIdDprd;
    private javax.swing.JTextField textPeriodeJabatan;
    // End of variables declaration//GEN-END:variables
}
