/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CRUD.crudFunction;
import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author USER
 */
public class framePeriodeKegiatan extends javax.swing.JFrame {

    private crudFunction CRUD;
    
    private String namaTabel = "tb_periode_kegiatan"; 
    private String primaryKey = "id_periode_kegiatan";
    private String fieldnya[] = {"id_periode_kegiatan", "id_dprd", "status", "tgl_kegiatan", "jam_kegiatan", "lokasi", "keperluan"};
    private String[] isinya;
    
    private String judulKolom[] = {"ID Periode Kegiatan", "ID DPRD", "Status", "Tanggal Kegiatan", "Jam Kegiatan", "Lokasi", "Keperluan"}; 
    private int lebarKolom[] = {100, 100, 150, 150, 150, 150, 150};
    private String SQL = "SELECT * FROM tb_periode_kegiatan ORDER BY id_periode_kegiatan ASC";
    
    /**
     * Creates new form framePeriodeKegiatan
     */
    public framePeriodeKegiatan() {
        
        CRUD = new crudFunction();
                
        isinya = new String[7];
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        loadData();
    }
    
    public void loadData(){
        CRUD.settingJudulTabel(tabelPeriodeKegiatan, judulKolom);
        CRUD.settingLebarKolom(tabelPeriodeKegiatan, lebarKolom);
        CRUD.tampilTabel(tabelPeriodeKegiatan, SQL, judulKolom);
    }
    
    private void updateIsinya() {
        isinya[0] = textIdPeriodeKegiatan.getText();
        isinya[1] = textIdDprd.getText();
        isinya[2] = textStatus.getSelectedItem().toString();
        isinya[3] = textTanggalKegiatan.getText();
        isinya[4] = textJamKegiatan.getText();
        isinya[5] = textLokasi.getText();
        isinya[6] = textKeperluan.getText();
    }
    
    private void bersih() {
        textIdPeriodeKegiatan.setText("");
        textIdDprd.setText("");
        textJamKegiatan.setText("");
        textKeperluan.setText("");
        textLokasi.setText("");
        textStatus.setSelectedItem("Aktif");
        textTanggalKegiatan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idPeriodeKegiatan = new javax.swing.JLabel();
        idDprd = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        tanggalKegiatan = new javax.swing.JLabel();
        jamKegiatan = new javax.swing.JLabel();
        lokasi = new javax.swing.JLabel();
        keperluan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textIdDprd = new javax.swing.JTextField();
        textTanggalKegiatan = new javax.swing.JTextField();
        textJamKegiatan = new javax.swing.JTextField();
        textKeperluan = new javax.swing.JTextField();
        textLokasi = new javax.swing.JTextField();
        textIdPeriodeKegiatan = new javax.swing.JTextField();
        textStatus = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBersih = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeriodeKegiatan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Frame Periode Kegiatan");
        setResizable(false);

        idPeriodeKegiatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idPeriodeKegiatan.setText("Id Periode Kegiatan");

        idDprd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idDprd.setText("Id DPRD");

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setText("Status");

        tanggalKegiatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tanggalKegiatan.setText("Tanggal Kegiatan");

        jamKegiatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jamKegiatan.setText("Jam Kegiatan");

        lokasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lokasi.setText("Lokasi");

        keperluan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keperluan.setText("Keperluan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDprd)
                    .addComponent(idPeriodeKegiatan)
                    .addComponent(tanggalKegiatan)
                    .addComponent(jamKegiatan)
                    .addComponent(keperluan)
                    .addComponent(lokasi)
                    .addComponent(status))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPeriodeKegiatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idDprd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggalKegiatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jamKegiatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lokasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keperluan)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        textTanggalKegiatan.setToolTipText("YYYY-MM-DD");

        textJamKegiatan.setToolTipText("24:60:60");
        textJamKegiatan.setName(""); // NOI18N

        textStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "NonAktif" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textIdPeriodeKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdDprd, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTanggalKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textJamKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKeperluan, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textIdPeriodeKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textIdDprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textTanggalKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textJamKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textKeperluan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(buttonSimpan);

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        jPanel4.add(buttonUbah);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel4.add(buttonHapus);

        buttonBersih.setText("Bersih");
        buttonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihActionPerformed(evt);
            }
        });
        jPanel4.add(buttonBersih);

        buttonCetak.setText("Cetak");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCetak);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Data Periode Kegiatan");
        jPanel3.add(jLabel1);

        tabelPeriodeKegiatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPeriodeKegiatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeriodeKegiatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeriodeKegiatan);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihActionPerformed
        // TODO add your handling code here:
        
        bersih();
        textIdPeriodeKegiatan.requestFocus();
    }//GEN-LAST:event_buttonBersihActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        
        updateIsinya();
        
        if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom terlebih dahulu jika ingin menggunakan tombol Simpan...!");
        } else {
            CRUD.SimpanDinamis(namaTabel, fieldnya, isinya);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdPeriodeKegiatan.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Harap isi 'Id Periode Kegiatan' yang ingin diubah jika ingin menggunakan tombol Ubah...!");
            bersih();
            textIdPeriodeKegiatan.requestFocus();
        } else if (Arrays.stream(isinya).anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang kosong jika ingin menggunakan tombol Ubah...!");
        } else {
            CRUD.UbahDinamis(namaTabel, primaryKey, isiPrimary, fieldnya, isinya);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        
        String isiPrimary = textIdPeriodeKegiatan.getText();
        updateIsinya();
        
        if (isiPrimary.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon isi 'Id Periode Kegiatan' yang ingin dihapus jika ingin menggunakan tombol Hapus...!");
            bersih();
            textIdPeriodeKegiatan.requestFocus();
        } else {
            CRUD.HapusDinamis(namaTabel, primaryKey, isiPrimary);
            loadData();
            bersih();
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tabelPeriodeKegiatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeriodeKegiatanMouseClicked
        // TODO add your handling code here:
        
        int row = tabelPeriodeKegiatan.getSelectedRow();

            if (row != -1) {
                String valueId = tabelPeriodeKegiatan.getValueAt(row, 0).toString();
                String valueIdDprd = tabelPeriodeKegiatan.getValueAt(row, 1).toString();
                String valueStatus = tabelPeriodeKegiatan.getValueAt(row, 2).toString();
                String valueTanggalKegiatan = tabelPeriodeKegiatan.getValueAt(row, 3).toString();
                String valueJamKegiatan = tabelPeriodeKegiatan.getValueAt(row, 4).toString();
                String valueLokasi = tabelPeriodeKegiatan.getValueAt(row, 5).toString();
                String valueKeperluan = tabelPeriodeKegiatan.getValueAt(row, 6).toString();

                textIdPeriodeKegiatan.setText(valueId);
                textIdDprd.setText(valueIdDprd);
                textStatus.setSelectedItem(valueStatus);
                textTanggalKegiatan.setText(valueTanggalKegiatan);
                textJamKegiatan.setText(valueJamKegiatan);
                textLokasi.setText(valueLokasi);
                textKeperluan.setText(valueKeperluan);
            }
    }//GEN-LAST:event_tabelPeriodeKegiatanMouseClicked

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        
        CRUD.cetakLaporan("laporanPeriodeKegiatan.jasper");
    }//GEN-LAST:event_buttonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePeriodeKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePeriodeKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePeriodeKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePeriodeKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePeriodeKegiatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBersih;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel idDprd;
    private javax.swing.JLabel idPeriodeKegiatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jamKegiatan;
    private javax.swing.JLabel keperluan;
    private javax.swing.JLabel lokasi;
    private javax.swing.JLabel status;
    private javax.swing.JTable tabelPeriodeKegiatan;
    private javax.swing.JLabel tanggalKegiatan;
    private javax.swing.JTextField textIdDprd;
    private javax.swing.JTextField textIdPeriodeKegiatan;
    private javax.swing.JTextField textJamKegiatan;
    private javax.swing.JTextField textKeperluan;
    private javax.swing.JTextField textLokasi;
    private javax.swing.JComboBox<String> textStatus;
    private javax.swing.JTextField textTanggalKegiatan;
    // End of variables declaration//GEN-END:variables
}
